server:
  port: 8766
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: userServer
          uri: ${user.server}
          predicates:
            - Path=/user/**
        - id: appServer
          uri: ${app.server}
          predicates:
            - Path=/app/**
        - id: gatewayServer
          uri: ${gateway.server}
          predicates:
            - Path=/test/fallback
          filters:
            - name: Hystrix
              args:
                name: gatewayServer
                fallbackUri: forward:/gateway/fallback
#user.server是常量名,可以任意配
#如果目标服务和gateway网关服务都注册到相同的eureka,想直接从eureka找服务,则该常量值必须以lb:开头,代表从eureka找服务
#如果目标服务和gateway网关服务并不都是注册到相同的eureka,也可以直接写死目标服务的地址
#user:
#  server: http://localhost:8764
user:
  server: lb://user-server
app:
  server: lb://app-server
gateway:
  server: lb://gateway-server
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    lease-expiration-duration-in-seconds: 7
    lease-renewal-interval-in-seconds: 3